### ISSUE TITLE
Submitting form didn't save fields value

### ISSUE THREAD

**Issue by Heine76** [weDevsOfficial/weforms#111] opened 2018-05-22 15:13 UTC
Hello,

To start i would make my  apologize for my approximative english.

The problem is :

When i answer to my [contact form](http://rmjcn.ownprod.com/contact/), the submission is saved in Database only with the ID's answer, all the values of my personnal fields stay blank.
 

After that,  my email notification works properly but naturally my variable stay blanck.

I've tried to put off all my extensions, uninstall and reinstall the plug-in without others extensions but the bug is persistant.

All others extensions works properly when i'm trying to saved something in database, like a form with an other extension.

I really have no idea about how to find the solution, if someone have an idea and could help me it's could be nice.

Thanks anyway.

**Comment by itowhid06** [comment] 2018-05-25 03:35
Hello @Heine76,

Are you still facing the issue? Please also try changing your theme and update your weForms to latest version. Let me know the updates.

**Comment by trapias** [comment] 2018-05-25 16:35
I have the same issue too: I just updated Wordpress to latest release and the plugin too, reverted to a standard theme but it does not save any field to database, with any form. 
Tried disabling most of plugins and no chances - what to look at?

I’m working on a dev site at Pantheon, if this can help.

**Comment by rafsuntaskin** [comment] 2018-05-25 19:14
@trapias ,

Looks like it might be some configuration issue on your end. Can you please install the [health-check](https://wordpress.org/plugins/health-check/) plugin and share the debug info?? 

Thanks

**Comment by Heine76** [comment] 2018-05-28 08:38
Hie all,

Thanks for your time, i'm still facing the issue.
I've install the health check and  here is the debug information : 

`
						### WordPress ###

Version: 4.9.6
Language: fr_FR
Permalink structure: /%postname%/
Is this site using HTTPS?: No
Can anyone register on this site?: No
Default comment status: closed
Is this a multisite?: No
User Count: 1
Communication with WordPress.org: WordPress.org is reachable
Create loopback requests: The loopback request to your site completed successfully.

### Active theme ###

Name: Twenty Seventeen
Version: 1.6
Author: the WordPress team
Author website: https://wordpress.org/
Parent theme: Not a child theme
Supported theme features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, starter-content, custom-header, widgets

### Other themes (4) ###

rmjcn (rmjcn): Version 1.0.0 by Underscores.me
rmjcn (test): Version 1.0.0 by Underscores.me
Twenty Fifteen (twentyfifteen): Version 2.0 by the WordPress team
Twenty Sixteen (twentysixteen): Version 1.5 by the WordPress team

### Must Use Plugins (1) ###

Health Check Disable Plugins: Version 1.3

### Active Plugins (1) ###

Health Check: Version 1.0.1 by The WordPress.org community

### Inactive Plugins (14) ###

Custom Facebook Feed: Version 2.6.1 by Smash Balloon
Google Analytics Dashboard for WP (GADWP): Version 5.3.3 by ExactMetrics team
Menu Image: Version 2.9.0 by Alex Davyskiba aka Zviryatko
Page Builder by SiteOrigin: Version 2.6.7 by SiteOrigin
Registrations for The Events Calendar: Version 2.2 by Roundup WP
SiteOrigin Widgets Bundle: Version 1.11.8 by SiteOrigin
Smart Slider 3: Version 3.2.14 by Nextend
The Events Calendar: Version 4.6.16 by Modern Tribe, Inc.
weForms: Version 1.2.8 by weDevs
Wordfence Security: Version 7.1.6 by Wordfence
WPFront Notification Bar: Version 1.7 by Syam Mohan
WP Responsive Menu: Version 3.0.3 by MagniGenie
WP Store Locator: Version 2.2.15 by Tijmen Smit
Yoast SEO: Version 7.5.1 by Team Yoast

### Media handling ###

Active editor: WP_Image_Editor_GD
Imagick Module Version: Imagick not available
ImageMagick Version: Imagick not available
GD Version: bundled (2.1.0 compatible)
Ghostscript Version: Not available

### Server ###

Server architecture: SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc
PHP Version: 7.0.30 
PHP SAPI: cgi-fcgi
PHP max input variables: 4000
PHP time limit: 120
PHP memory limit: 256M
Max input time: 60
Upload max filesize: 64M
PHP post max size: 76M
cURL Version: 7.50.3 OpenSSL/1.0.2j
SUHOSIN installed: No
Is the Imagick library available: No

### Database ###

Extension: mysqli
Server version: 5.6.40-log
Client version: 5.5.52
Database prefix: rmjcn_

### WordPress constants ###

ABSPATH: /mnt/web306/d0/16/58740016/htdocs/RMJCN/
WP_HOME: Undefined
WP_SITEURL: Undefined
WP_DEBUG: Disabled
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG_DISPLAY: Enabled
WP_DEBUG_LOG: Disabled
SCRIPT_DEBUG: Disabled
WP_CACHE: Disabled
CONCATENATE_SCRIPTS: Undefined
COMPRESS_SCRIPTS: Undefined
COMPRESS_CSS: Undefined
WP_LOCAL_DEV: Undefined

### Filesystem permissions ###

The main WordPress directory: Writable
The wp-content directory: Writable
The uploads directory: Writable
The plugins directory: Writable
The themes directory: Writable
The Must Use Plugins directory: Writable

`
I'm missing for two weeks from tomorrow, i'm still reading during this time but i will have no access on my project during this time.
Sorry for that but we will continue

**Comment by trapias** [comment] 2018-05-28 08:51
@Heine76 just installed locally on my mac, and here it's working properly: will do the "health-check" thing at the other site asap.

**Comment by Heine76** [comment] 2018-06-13 09:02
Hello again,
Sorry for my absence.

I'm back now and ready to find the solution with all of you.

I'm still facing the issue and nothing is new since the last two weeks.

I'm going to install an other environment to test the plug-in and compared the database and other stuff with my bugued version

**Comment by danielschils** [comment] 2018-06-16 11:04
Hi !

I have the same problem, only the numbers of the entries is saved in the list of the entries, no other datas.

Could you help me to solve this problem ?
Wordpress 4.9.6 
Theme ENFOLD 4.4.1 up to date

Thanks a lot.

Daniel

**Comment by Heine76** [comment] 2018-06-18 09:57
Hie daniel,

i havn't solved the issue actually, i need some help to solved that. 
Anyway if i find the issue without a wedev developers, i'm gonna write the solution here.

**Comment by Heine76** [comment] 2018-06-18 14:45
I've tried weforms on a new virgin wordpress with a basic theme (twenty seventeen version 1.3 - older than the actual 1.6)

I think  it isn't the consequence of any manipulation or configuration of wordpress but more a problem with the configuration of our server.

@danielschils if you can check and paste your configuration with healthcheck (like me at the beggining) it's can be helpfull for me and wedev's developers i think.

Thanks ;)

**Comment by rafsuntaskin** [comment] 2018-07-20 04:00
Thanks Everyone for your response and as this is an issue for Server Environment which we were unable to reproduce therefore closing this issue for now. But if any of you are still facing similar issue after updating to latest version we will help you out.

**Closed by rafsuntaskin** 2018-07-20 04:00 UTC
